-- 011_v0_4_taxa_identity.sql
-- Make taxa_id auto-generated so CSVs without IDs can import cleanly.

begin;

-- Add identity to taxa.taxa_id if not already present
do $$
begin
  -- If the column already has identity, do nothing
  if exists (
    select 1
    from information_schema.columns c
    where c.table_schema = 'public'
      and c.table_name = 'taxa'
      and c.column_name = 'taxa_id'
      and c.is_identity = 'YES'
  ) then
    -- no-op
    return;
  end if;

  execute 'alter table public.taxa alter column taxa_id add generated by default as identity';
end $$;

commit;

